development:
  adapter: postgresql
  database: resumes_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: resumes_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: resumes_production
  pool: 5
  timeout: 5000
